# Generated by Django 5.0.1 on 2024-01-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("flag", models.CharField(max_length=255)),
                ("capital", models.CharField(max_length=255)),
                ("timezone", models.CharField(max_length=255)),
                ("googlemap", models.CharField(max_length=255)),
                ("openstreet", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "countries",
            },
        ),
    ]
